server:
  port: 81

spring:
  application:
    name: cloud-order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/db_2023?characterEncoding=utf-8&useSSL=false
    username: root
    password: Lhj2001124111

eureka:
  client:
    # 表示将自己注册进eurekaServer
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

