server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment-routh1
          uri: http://localhost:8001
          predicates:
            - Path=/payment/get/**

        - id: payment-routh2
          uri: http://localhost:8001
          predicates:
            - Path=/payment/lb/**
            - After=2023-06-13T14:31:08.448+08:00[Asia/Shanghai]
            - Cookie=username,povlean


eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka/